config/routes.rb
Mobilestore::Application.routes.draw do
  get "faq/answer1"

  get "faq/answer2"

  get "faq/answer3"

  get "faq/answer4"

  get "faq/answer5"

  resources :questions
  match '/myindex' => 'questions#myindex'

  get "orderitems/index"

  get "orderitems/show"

  get "orderitems/new"

  get "orderitems/edit"

  resources :orders do
    resources :orderitems
  end

  get "cart/index"
  match '/cart' => 'cart#index'
  match '/cart/:id' => 'cart#add'
  match '/cart/remove/:id' => 'cart#remove'
  match '/clearCart' => 'cart#clearCart'
  match '/checkout' => 'orders#new'
  resources :forums do
    resources :commentfs
  end

  resources :posts do
    resources :commentps
  end

  resources :profiles
  match '/myprofile' => 'profiles#myprofile'

  devise_for :users do
    resources :orders
  end

  get "site/about"
  get "site/contact"
  get "site/frequent_ask_questions"
  get "site/site_map"
  get "site/game"
  match '/about' => 'site#about'
  match '/contact' => 'site#contact'
  match '/frequent_ask_questions' => 'site#frequent_ask_questions'
  match '/site_map' => 'site#site_map'
  match '/game'=> 'site#game'

  get "home/index"
  get "home/thank_you"
  match '/index' => 'home#index'
  match '/thank_you' => 'home#thank_you'

  resources :items
  match '/category/:id' => 'items#category'
  match '/brand/:id' => 'items#brand'

  root :to => 'home#index'

end

app/models/commentf.rb
class Commentf < ActiveRecord::Base
  belongs_to :forum
  belongs_to :user
  attr_accessible :body, :user_id
  validates :body, presence: true,
            length: { minimum: 10 }
end

app/models/commentp.rb
class Commentp < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body
  validates :body, presence: true,
  length: { minimum: 10 }
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :text, :title
  has_many :commentfs, dependent: :destroy
  belongs_to :user
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :text, presence: true,
            length: { minimum: 10 }
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :brand, :category, :description, :image_url, :price, :title, :discount
  DISCOUNT = [ "10% off", "20% off", "30% off", "40% off", "half price", "full price" ]
  validates :title, :description, :image_url, :brand, :category, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
      with:    %r{\.(gif|jpg|png)\Z}i,
      message: 'must be a URL for GIF, JPG or PNG image.'
  }
  def self.search(search_query)
    if search_query
      find(:all,:conditions => ['title LIKE ?', "%#{
      search_query}%"])
    else
      find(:all)
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :orderitems, dependent: :destroy
  attr_accessible :order_date, :receiver_address, :receiver_mobile, :receiver_name, :user_id
  validates :receiver_name, :receiver_address, presence: true
  validates :receiver_mobile, format: { with: /08\d{8}/, message: "is not a valid mobile number" }
  validates :receiver_mobile, presence: true,
            length: { maximum: 10 }
end

class Collectorders < Order
  attr_accessor :handle
  def initialize (filename)
    @handle = File.open(filename, 'a')
  end
  def addorder (name, address, mobile, date)
    neworder = "#{name},#{address},#{mobile},#{date}"
    @handle.puts(neworder)
  end
  def addorderitems (itemtitle,price,quantity,totalprice)
    neworderitem = "#{itemtitle},#{price},#{quantity},#{totalprice}"
    @handle.puts (neworderitem)
  end
  def totalprice(totalprice)
    newtotal = "#{totalprice}"
    @handle.puts (newtotal)
  end
  def blankline
    @handle.write("\n")
  end
end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
  attr_accessible :description, :item_id, :price, :quantity, :title
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :text, :title
  has_many :commentps, dependent: :destroy
  belongs_to :user
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :text, presence: true,
            length: { minimum: 10 }
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  attr_accessible :address, :firstname, :lastname, :mobile,:user_id
  validates :user_id, uniqueness: true
  validates :firstname, :lastname, :address, presence: true
  validates :mobile, format: { with: /08\d{8}/, message: "is not a valid mobile number" }
  validates :mobile, presence: true,
            length: { maximum: 10 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :mobile, :name, :your_question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :profiles
  has_many :posts
  has_many :forums
  has_many :orders
  has_many :commentfs
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!, :except  => [:new, :create]
  before_filter :ensure_staff, :except => [:new, :create]
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  def myindex
    @questions = Question.all

    respond_to do |format|
      format.html {render :layout => false}
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html {render :layout => false}# show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new

    @question = Question.new

    respond_to do |format|
      format.html { render :layout => false } # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
    render :layout => false
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/commentfs_helper.rb
module CommentfsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

          <ul>
            <% @question.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :Your_name %>
      <br/>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :Your_mobile %>
      <br/>
      <%= f.text_field :mobile %>
    </div>
    <div class="field">
      <%= f.label :your_question %>
      <br/>
      <%= f.text_area :your_question, :rows => 6 %>
    </div>
    <div class="actions">
      <%= f.submit 'submit' %>
    </div>
<% end %>

app/views/questions/destroy.js.erb
$('.delete_question').bind('ajax:success', function() {
    $(this).closest('tr').fadeOut('slow');
    $("#textmessage").empty();
});

app/views/questions/edit.html.erb
<h1>Editing a question</h1>
  <br/>    <br/>
<%= render 'form' %>

<%= link_to 'Show', @question, :class => 'show_question' %> |
<%= link_to 'Back', myindex_url, :class => 'myindex' %>

<script type="text/javascript">
    var show_myindex = function (e) {
        e.preventDefault();
        $("#textmessage").empty();
        $("#show_edit_area").empty();
        var url = $(this).attr("href");
        $.get(url, function (data) {
            $("#question_index").hide().html(data).fadeIn('slow');
        });
    }
    $(".show_question").on("click", show_a_question);
    $(".myindex").on("click", show_myindex);
</script>

app/views/questions/index.html.erb
<div id="show_edit_area"></div>
<div id="textmessage"></div>
<div id="question_index">
<center><h1>Customer questions</h1></center>  <br/><br/><br/>

<table width="100%">
  <tr>
    <th>Name</th>
    <th>Mobile</th>
    <th>Your question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.name %></td>
    <td><%= question.mobile %></td>
    <td><%= question.your_question %></td>
    <td><%= link_to 'Show', question, :class => 'show_question' %></td>
    <td><%= link_to 'Edit', edit_question_path(question), :class => 'edit_question' %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_question'  %></td>
  </tr>
<% end %>
</table>

<br />

<% link_to 'New Question', new_question_path %>
</div>
<script type="text/javascript" src="/assets/questionindex.js"></script>

app/views/questions/myindex.html.erb
<center><h1>Customer questions</h1></center>  <br/><br/><br/>

<table width="100%">
  <tr>
    <th>Name</th>
    <th>Mobile</th>
    <th>Your question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @questions.each do |question| %>
      <tr>
        <td><%= question.name %></td>
        <td><%= question.mobile %></td>
        <td><%= question.your_question %></td>
        <td><%= link_to 'Show', question, :class => 'show_question' %></td>
        <td><%= link_to 'Edit', edit_question_path(question), :class => 'edit_question' %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_question'  %></td>
      </tr>
  <% end %>
</table>

<br />

<% link_to 'New Question', new_question_path %>
<script type="text/javascript" src="/assets/questionindex.js"></script>

app/views/questions/new.html.erb
<div id="question_new"><%= render 'form' %>
</div>
<% link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><% notice %></p>
<h1>Showing a question</h1>
<br/>
<p>
  <b>Name:</b>
  <%= @question.name %>
</p>

<p>
  <b>Mobile:</b>
  <%= @question.mobile %>
</p>

<p>
  <b>Your question:</b>
  <%= @question.your_question %>
</p>


<%= link_to 'Edit', edit_question_path(@question), :class => 'edit_question' %> |
<%= link_to 'Back', myindex_url, :class => 'myindex' %>
<script type="text/javascript">
    var show_myindex = function (e) {
        e.preventDefault();
        $("#textmessage").empty();
        $("#show_edit_area").empty();
        var url = $(this).attr("href");
        $.get(url, function (data) {
            $("#question_index").hide().html(data).fadeIn('slow');
        });
    }
    $(".edit_question").on("click", edit_a_question);
    $(".myindex").on("click", show_myindex);
</script>