config/routes.rb
Mobilestore::Application.routes.draw do
  get "faq/answer1"

  get "faq/answer2"

  get "faq/answer3"

  get "faq/answer4"

  get "faq/answer5"

  resources :questions
  match '/myindex' => 'questions#myindex'

  get "orderitems/index"

  get "orderitems/show"

  get "orderitems/new"

  get "orderitems/edit"

  resources :orders do
    resources :orderitems
  end

  get "cart/index"
  match '/cart' => 'cart#index'
  match '/cart/:id' => 'cart#add'
  match '/cart/remove/:id' => 'cart#remove'
  match '/clearCart' => 'cart#clearCart'
  match '/checkout' => 'orders#new'
  resources :forums do
    resources :commentfs
  end

  resources :posts do
    resources :commentps
  end

  resources :profiles
  match '/myprofile' => 'profiles#myprofile'

  devise_for :users do
    resources :orders
  end

  get "site/about"
  get "site/contact"
  get "site/frequent_ask_questions"
  get "site/site_map"
  get "site/game"
  match '/about' => 'site#about'
  match '/contact' => 'site#contact'
  match '/frequent_ask_questions' => 'site#frequent_ask_questions'
  match '/site_map' => 'site#site_map'
  match '/game'=> 'site#game'

  get "home/index"
  get "home/thank_you"
  match '/index' => 'home#index'
  match '/thank_you' => 'home#thank_you'

  resources :items
  match '/category/:id' => 'items#category'
  match '/brand/:id' => 'items#brand'

  root :to => 'home#index'

end

app/models/commentf.rb
class Commentf < ActiveRecord::Base
  belongs_to :forum
  belongs_to :user
  attr_accessible :body, :user_id
  validates :body, presence: true,
            length: { minimum: 10 }
end

app/models/commentp.rb
class Commentp < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body
  validates :body, presence: true,
  length: { minimum: 10 }
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :text, :title
  has_many :commentfs, dependent: :destroy
  belongs_to :user
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :text, presence: true,
            length: { minimum: 10 }
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :brand, :category, :description, :image_url, :price, :title, :discount
  DISCOUNT = [ "10% off", "20% off", "30% off", "40% off", "half price", "full price" ]
  validates :title, :description, :image_url, :brand, :category, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
      with:    %r{\.(gif|jpg|png)\Z}i,
      message: 'must be a URL for GIF, JPG or PNG image.'
  }
  def self.search(search_query)
    if search_query
      find(:all,:conditions => ['title LIKE ?', "%#{
      search_query}%"])
    else
      find(:all)
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :orderitems, dependent: :destroy
  attr_accessible :order_date, :receiver_address, :receiver_mobile, :receiver_name, :user_id
  validates :receiver_name, :receiver_address, presence: true
  validates :receiver_mobile, format: { with: /08\d{8}/, message: "is not a valid mobile number" }
  validates :receiver_mobile, presence: true,
            length: { maximum: 10 }
end

class Collectorders < Order
  attr_accessor :handle
  def initialize (filename)
    @handle = File.open(filename, 'a')
  end
  def addorder (name, address, mobile, date)
    neworder = "#{name},#{address},#{mobile},#{date}"
    @handle.puts(neworder)
  end
  def addorderitems (itemtitle,price,quantity,totalprice)
    neworderitem = "#{itemtitle},#{price},#{quantity},#{totalprice}"
    @handle.puts (neworderitem)
  end
  def totalprice(totalprice)
    newtotal = "#{totalprice}"
    @handle.puts (newtotal)
  end
  def blankline
    @handle.write("\n")
  end
end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
  attr_accessible :description, :item_id, :price, :quantity, :title
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :text, :title
  has_many :commentps, dependent: :destroy
  belongs_to :user
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :text, presence: true,
            length: { minimum: 10 }
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  attr_accessible :address, :firstname, :lastname, :mobile,:user_id
  validates :user_id, uniqueness: true
  validates :firstname, :lastname, :address, presence: true
  validates :mobile, format: { with: /08\d{8}/, message: "is not a valid mobile number" }
  validates :mobile, presence: true,
            length: { maximum: 10 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :mobile, :name, :your_question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :profiles
  has_many :posts
  has_many :forums
  has_many :orders
  has_many :commentfs
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = current_user.profiles
    @posts = current_user.posts
    @forums = current_user.forums
    @orders = current_user.orders
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = current_user.profiles.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = current_user.profiles.new(params[:profile])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = current_user.profiles.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_user.profiles.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = current_user.profiles.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = current_user.profiles.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

#  def myprofile
#    profile = Profile.find_by_user_id(current_user.id)
#    if profile.nil?
#      redirect_to "/profiles/new"
#    else
#      @user = User.find(current_user.id)
#      @profile = Profile.find_by_user_id(@user.id)
#      redirect_to "/profiles/#{@profile.id}"
#    end
#  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/commentfs_helper.rb
module CommentfsHelper
end

app/helpers/commentps_helper.rb
module CommentpsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
    <% if @profile.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

          <ul>
            <% @profile.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :firstname %>
      <br/>
      <%= f.text_field :firstname %>
    </div>
    <div class="field">
      <%= f.label :lastname %>
      <br/>
      <%= f.text_field :lastname %>
    </div>
    <div class="field">
      <%= f.label :address %>
      <br/>
      <%= f.text_area :address, :rows => 9 %>
    </div>
    <div class="field">
      <%= f.label :mobile %>
      <br/>
      <%= f.text_field :mobile %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/profiles/edit.html.erb
<div id="profile_edit">
<h1>Editing profile</h1>
   </br>
<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>
  </div>

app/views/profiles/index.html.erb
<div id="profile_index">
  <% if not @profiles.blank? %>
      <h1>Your profile</h1>
      <br/>

      <table width="100%">
        <tr>
          <th>Firstname</th>
          <th>Lastname</th>
          <th>Address</th>
          <th>Mobile</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @profiles.each do |profile| %>
            <tr>
              <td><%= profile.firstname %></td>
              <td><%= profile.lastname %></td>
              <td><%= profile.address %></td>
              <td><%= profile.mobile %></td>
              <td><%= link_to 'Show', profile %></td>
              <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
              <td><%= link_to 'Destroy', profile, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
      </table>

      <br/>
  <% else %>
      <center>
        <%= link_to 'Create Your Profile', new_profile_path %>
      </center>
      <br/>
  <% end %>
  <br/>
  <hr/>
  <br/>
  <% if not @posts.blank? %>
      <h1>Your posts</h1>
      <br/>
      <table width="100%">
        <tr>
          <th>Title</th>
          <th>Text</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @posts.each do |post| %>
            <tr>
              <td><%= post.title %></td>
              <td><%= truncate(strip_tags(post.text),
                               length: 16)  %></td>
              <td><%= link_to 'Show', post %></td>
              <td><%= link_to 'Edit', edit_post_path(post) %></td>
              <td><%= link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
      </table>
      <br/>
  <% else %>
      <p align="center">You haven't post anything yet!</p>
  <% end %>
  <br>
  <hr/>
  <br/>
  <% if not @forums.blank? %>
      <h1>Your topics in the forum</h1>
      <br/>
      <table width="100%">
        <tr>
          <th>Discussion</th>
          <th>Start by</th>
          <th>Replies</th>
          <th>Last post</th>
          <th></th>
          <th></th>
        </tr>

        <% @forums.each do |forum| %>
            <tr>
              <td><%= link_to truncate(strip_tags(forum.title),
                                       length: 30), forum %></td>
              <td>
                <% if forum.user.profiles.first != nil %>
                    <%= forum.user.profiles.first.firstname %>
                <% else %>
                    <%= forum.user.email %>
                <% end %></td>
              <td><%= forum.commentfs.length %></td>
              <td>
                <% if forum.commentfs.length != 0 %>
                    <% if forum.commentfs.last.user.profiles.first != nil %>
                        <%= forum.commentfs.last.user.profiles.first.firstname %>
                    <% else %>
                        <%= forum.commentfs.last.user.email %>
                    <% end %>
                <% else %>
                    No replies!
                <% end %></td>
              <td><%= link_to 'Edit', edit_forum_path(forum) %></td>
              <td><%= link_to 'Destroy', forum, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
      </table>

      <br/>
  <% else %>
      <p align="center">You haven't upload any topic yet.</p>
  <% end %>
  <br/>
  <hr/>
  <br/>
  <% if not @orders.blank? %>
      <h1>Your Shopping History</h1>
      <br/>
      <table width="100%">
        <tr>
          <th>Receiver name</th>
          <th>Receiver address</th>
          <th>Receiver mobile</th>
          <th>Order date</th>
          <th></th>
        </tr>

        <% @orders.each do |order| %>
            <tr>
              <td><%= order.receiver_name %></td>
              <td><%= order.receiver_address %></td>
              <td><%= order.receiver_mobile %></td>
              <td><%= order.order_date %></td>
              <td><%= link_to 'Show', order %></td>
            </tr>
        <% end %>
      </table>
  <% else %>
      <% if current_user and current_user.admin == 'customer' %>
          <p align="center">You have no shopping history yet.</p>
      <% end %>
  <% end %>
</div>

app/views/profiles/new.html.erb
<div id="profile_new">
<h1>New profile</h1>
   </br>
<%= render 'form' %>

<%= link_to 'Back', profiles_path %>
 </div>

app/views/profiles/show.html.erb
<p id="notice">
  <% notice %></p>
<div id="profile_show">
  <br/>

  <p>
    <b>Firstname:</b>
    <%= @profile.firstname %>
  </p>

  <p>
    <b>Lastname:</b>
    <%= @profile.lastname %>
  </p>

  <p>
    <b>Address:</b>
    <%= @profile.address %>
  </p>

  <p>
    <b>Mobile:</b>
    <%= @profile.mobile %>
  </p>

  <br/>


  <%= link_to 'Edit', edit_profile_path(@profile) %> |
  <%= link_to 'Back', profiles_path %>
</div>