config/routes.rb
Mobilestore::Application.routes.draw do
  get "faq/answer1"

  get "faq/answer2"

  get "faq/answer3"

  get "faq/answer4"

  get "faq/answer5"

  resources :questions
  match '/myindex' => 'questions#myindex'

  get "orderitems/index"

  get "orderitems/show"

  get "orderitems/new"

  get "orderitems/edit"

  resources :orders do
    resources :orderitems
  end

  get "cart/index"
  match '/cart' => 'cart#index'
  match '/cart/:id' => 'cart#add'
  match '/cart/remove/:id' => 'cart#remove'
  match '/clearCart' => 'cart#clearCart'
  match '/checkout' => 'orders#new'
  resources :forums do
    resources :commentfs
  end

  resources :posts do
    resources :commentps
  end

  resources :profiles
  match '/myprofile' => 'profiles#myprofile'

  devise_for :users do
    resources :orders
  end

  get "site/about"
  get "site/contact"
  get "site/frequent_ask_questions"
  get "site/site_map"
  get "site/game"
  match '/about' => 'site#about'
  match '/contact' => 'site#contact'
  match '/frequent_ask_questions' => 'site#frequent_ask_questions'
  match '/site_map' => 'site#site_map'
  match '/game'=> 'site#game'

  get "home/index"
  get "home/thank_you"
  match '/index' => 'home#index'
  match '/thank_you' => 'home#thank_you'

  resources :items
  match '/category/:id' => 'items#category'
  match '/brand/:id' => 'items#brand'

  root :to => 'home#index'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :text, :title
  has_many :commentfs, dependent: :destroy
  belongs_to :user
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :text, presence: true,
            length: { minimum: 10 }
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all.sort {|a, b|
      a_time = if a.commentfs.last then a.commentfs.last.created_at else a.created_at end
      b_time = if b.commentfs.last then b.commentfs.last.created_at else b.created_at end

      b_time <=> a_time
    }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @forums }
    end
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    @forum = Forum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @forum }
    end
  end

  # GET /forums/new
  # GET /forums/new.json
  def new
    @forum = Forum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @forum }
    end
  end

  # GET /forums/1/edit
  def edit
    if current_user and current_user.admin == 'manager'
      @forum = Forum.find(params[:id])
    else
      if (current_user and current_user.admin == 'customer') or (current_user and current_user.admin == 'worker')
        @forum = current_user.forums.find(params[:id])
      end
    end
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = current_user.forums.new(params[:forum])

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render json: @forum, status: :created, location: @forum }
      else
        format.html { render action: "new" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /forums/1
  # PUT /forums/1.json
  def update
    if current_user and current_user.admin == 'manager'
      @forum = Forum.find(params[:id])
    else
      if (current_user and current_user.admin == 'customer') or (current_user and current_user.admin == 'worker')
        @forum = current_user.forums.find(params[:id])
      end
    end
    respond_to do |format|
      if @forum.update_attributes(params[:forum])
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    if current_user and current_user.admin == 'manager'
      @forum = Forum.find(params[:id])
      @forum.destroy
    else
      if (current_user and current_user.admin == 'customer') or (current_user and current_user.admin == 'worker')
        @forum = current_user.forums.find(params[:id])
        @forum.destroy
      end
    end

    respond_to do |format|
      format.html {
        if current_user and current_user.admin == 'manager'
          redirect_to forums_url
        else
          redirect_to profiles_url
        end
      }
      format.json { head :no_content }
    end
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum) do |f| %>
    <% if @forum.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

          <ul>
            <% @forum.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <br/>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :text %>
      <br/>
      <%= f.text_area :text, :rows => 16 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/forums/edit.html.erb
<div id="forum_edit">
<h1>Editing forum</h1>
         <br/>
<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<% if (current_user and current_user.admin == 'customer') or (current_user and current_user.admin == 'worker') %>
    <%= link_to 'Back to Yoursite', profiles_path %>

<% else %>
    <%= link_to 'Back', forums_path %>
<% end %>
    </div>

app/views/forums/index.html.erb
<div id='forum_index'>

  <h1>Star Mobile forum</h1>
  <br/>
  <center>
    <button><%= link_to 'Add a new topic', new_forum_path %></button>
  </center>
  <br/> <br/><br/>
  <table>
    <tr>
      <th>Discussion</th>
      <th>Start by</th>
      <th>Replies</th>
      <th>Last post</th>
      <th></th>
      <th></th>
    </tr>
    <% @forums.each do |forum| %>
        <tr>
          <td><%= link_to truncate(strip_tags(Filteranddiscount.runfilter(forum.title)),
                                   length: 30), forum %></td>
          <td>
            <% if forum.user.profiles.first != nil %>
                <%= forum.user.profiles.first.firstname %>
            <% else %>
                <%= forum.user.email %>
            <% end %></td>
          <td><%= forum.commentfs.length %></td>
          <td>
            <% if forum.commentfs.length != 0 %>
            <% if forum.commentfs.last.user.profiles.first != nil %>
                <%= forum.commentfs.last.user.profiles.first.firstname %>
            <% else %>
                <%= forum.commentfs.last.user.email %>
            <% end %>
            <% else %>
                No replies!
            <% end %></td>
          <% if current_user and current_user.admin == 'manager' %>
              <td><%= link_to 'Edit', edit_forum_path(forum) %></td>
              <td><%= link_to 'Destroy', forum, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          <% end %>
        </tr>
    <% end %>
  </table>

  <br/>


</div>

app/views/forums/new.html.erb
<div id="forum_edit">
<h1>New forum</h1>
  <br/>
<%= render 'form' %>

<%= link_to 'Back', forums_path %>
 </div>

app/views/forums/show.html.erb
<p id="notice">
  <% notice %></p>

<div id="forum_show">
  <fieldset>
    <div>
      <h1><%= Filteranddiscount.runfilter(@forum.title) %></h1>

      <p>
        <b>Started by:</b>
        <% if @forum.user.profiles.first != nil %>
            <%= @forum.user.profiles.first.firstname %>
        <% else %>
            <%= @forum.user.email %>
        <% end %>
      </p>
    </div>
    <hr/>
    <p>
      <%= Filteranddiscount.runfilter(@forum.text) %>
    </p>
  </fieldset>
  <br/>

  <% @forum.commentfs.each do |commentf| %>
      <fieldset id="comment">
        <b>Re:</b><%= Filteranddiscount.runfilter(@forum.title) %>  <br/>
        <b> By: </b>
        <% if commentf.user.profiles.first != nil %>
            <%= commentf.user.profiles.first.firstname %>
        <% else %>
            <%= commentf.user.email %>
        <% end %>

        <hr/>
        <p>
          <%= Filteranddiscount.runfilter(commentf.body) %>
        </p>


        <% if current_user and current_user.admin == 'manager' %>
            <p>
              <%= link_to 'Destroy Comment', [commentf.forum, commentf],
                          method: :delete,
                          data: {confirm: 'Are you sure?'} %>
            </p>
        <% end %>  </fieldset>
      <br/>
  <% end %>
  <div id="reply">
    <h2>Reply here</h2>
    <%= form_for([@forum, @forum.commentfs.build]) do |f| %>

        <p>

          <%= f.text_area :body, :rows => 8 %>
        </p>

        <p>
          <%= f.submit 'submit' %>
        </p>
    <% end %>
  </div>
  <% if (current_user and current_user.admin == 'customer') or (current_user and current_user.admin == 'worker') %>
      <%= link_to 'View Forum', forums_path %> |
      <%= link_to 'View Yoursite', profiles_path %>

  <% else %>
      |<%= link_to 'Back', forums_path %>|
  <% end %>
</div>