config/routes.rb
Mobilestore::Application.routes.draw do
  get "faq/answer1"

  get "faq/answer2"

  get "faq/answer3"

  get "faq/answer4"

  get "faq/answer5"

  resources :questions
  match '/myindex' => 'questions#myindex'

  get "orderitems/index"

  get "orderitems/show"

  get "orderitems/new"

  get "orderitems/edit"

  resources :orders do
    resources :orderitems
  end

  get "cart/index"
  match '/cart' => 'cart#index'
  match '/cart/:id' => 'cart#add'
  match '/cart/remove/:id' => 'cart#remove'
  match '/clearCart' => 'cart#clearCart'
  match '/checkout' => 'orders#new'
  resources :forums do
    resources :commentfs
  end

  resources :posts do
    resources :commentps
  end

  resources :profiles
  match '/myprofile' => 'profiles#myprofile'

  devise_for :users do
    resources :orders
  end

  get "site/about"
  get "site/contact"
  get "site/frequent_ask_questions"
  get "site/site_map"
  get "site/game"
  match '/about' => 'site#about'
  match '/contact' => 'site#contact'
  match '/frequent_ask_questions' => 'site#frequent_ask_questions'
  match '/site_map' => 'site#site_map'
  match '/game'=> 'site#game'

  get "home/index"
  get "home/thank_you"
  match '/index' => 'home#index'
  match '/thank_you' => 'home#thank_you'

  resources :items
  match '/category/:id' => 'items#category'
  match '/brand/:id' => 'items#brand'

  root :to => 'home#index'

end

app/models/commentf.rb
class Commentf < ActiveRecord::Base
  belongs_to :forum
  belongs_to :user
  attr_accessible :body, :user_id
  validates :body, presence: true,
            length: { minimum: 10 }
end

app/models/commentp.rb
class Commentp < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body
  validates :body, presence: true,
  length: { minimum: 10 }
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :text, :title
  has_many :commentfs, dependent: :destroy
  belongs_to :user
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :text, presence: true,
            length: { minimum: 10 }
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :brand, :category, :description, :image_url, :price, :title, :discount
  DISCOUNT = [ "10% off", "20% off", "30% off", "40% off", "half price", "full price" ]
  validates :title, :description, :image_url, :brand, :category, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
      with:    %r{\.(gif|jpg|png)\Z}i,
      message: 'must be a URL for GIF, JPG or PNG image.'
  }
  def self.search(search_query)
    if search_query
      find(:all,:conditions => ['title LIKE ?', "%#{
      search_query}%"])
    else
      find(:all)
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :orderitems, dependent: :destroy
  attr_accessible :order_date, :receiver_address, :receiver_mobile, :receiver_name, :user_id
  validates :receiver_name, :receiver_address, presence: true
  validates :receiver_mobile, format: { with: /08\d{8}/, message: "is not a valid mobile number" }
  validates :receiver_mobile, presence: true,
            length: { maximum: 10 }
end

class Collectorders < Order
  attr_accessor :handle
  def initialize (filename)
    @handle = File.open(filename, 'a')
  end
  def addorder (name, address, mobile, date)
    neworder = "#{name},#{address},#{mobile},#{date}"
    @handle.puts(neworder)
  end
  def addorderitems (itemtitle,price,quantity,totalprice)
    neworderitem = "#{itemtitle},#{price},#{quantity},#{totalprice}"
    @handle.puts (neworderitem)
  end
  def totalprice(totalprice)
    newtotal = "#{totalprice}"
    @handle.puts (newtotal)
  end
  def blankline
    @handle.write("\n")
  end
end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
  attr_accessible :description, :item_id, :price, :quantity, :title
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :text, :title
  has_many :commentps, dependent: :destroy
  belongs_to :user
  validates :title, presence: true,
            length: { minimum: 5 }
  validates :text, presence: true,
            length: { minimum: 10 }
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  attr_accessible :address, :firstname, :lastname, :mobile,:user_id
  validates :user_id, uniqueness: true
  validates :firstname, :lastname, :address, presence: true
  validates :mobile, format: { with: /08\d{8}/, message: "is not a valid mobile number" }
  validates :mobile, presence: true,
            length: { maximum: 10 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :mobile, :name, :your_question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :profiles
  has_many :posts
  has_many :forums
  has_many :orders
  has_many :commentfs
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all(:order => "created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    if current_user and current_user.admin == 'manager'
      @post = Post.find(params[:id])
    else
      if (current_user and current_user.admin == 'customer') or (current_user and current_user.admin == 'worker')
        @post = current_user.posts.find(params[:id])
      end
    end

  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    if current_user and current_user.admin == 'manager'
      @post = Post.find(params[:id])
    else
      if (current_user and current_user.admin == 'customer') or (current_user and current_user.admin == 'worker')
        @post = current_user.posts.find(params[:id])
      end
    end
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if current_user and current_user.admin == 'manager'
      @post = Post.find(params[:id])
      @post.destroy
    else
      if (current_user and current_user.admin == 'customer') or (current_user and current_user.admin == 'worker')
        @post = current_user.posts.find(params[:id])
        @post.destroy
      end
    end
    respond_to do |format|
      format.html {
        if current_user and current_user.admin == 'manager'
          redirect_to posts_url
        else
          redirect_to profiles_url
        end
      }
      format.json { head :no_content }
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/commentfs_helper.rb
module CommentfsHelper
end

app/helpers/commentps_helper.rb
module CommentpsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <br/>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :text %>
      <br/>
      <%= f.text_area :text, :rows => 16 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<div id="post_edit">
<h1>Editing post</h1>
  <br/>
<%= render 'form' %>

<%= link_to 'Show', @post %> |
<% if (current_user and current_user.admin == 'customer') or (current_user and current_user.admin == 'worker') %>
    <%= link_to 'Back to Mysite', profiles_path %>

<% else %>
     <%= link_to 'Back', posts_path %>
<% end %>
                      </div>

app/views/posts/index.html.erb
<div id="post_index">
  <div align="center">..................</div>
  <h1 align="center">Posts</h1>


  <div align="center">..................</div>
  <br/>
  <% @posts.each do |post| %>
      <br/>
      <div id="post_index_title"><%= Filteranddiscount.runfilter(post.title) %></div>
      <br/>

      <div id="post_index_text"><%= truncate(strip_tags(Filteranddiscount.runfilter(post.text)),
                                             length: 280) %></div>
      <br/>

      <div id="post_index_link"><%= link_to 'Continue reading', post %>
        <% if current_user and current_user.admin == 'manager' %>
            <%= link_to 'Edit', edit_post_path(post) %>
            <%= link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'} %>
        <% end %>   </div>
      <br/>

      <div align="center">**************************************************************************</div>
  <% end %>


  <br/>
  <div id="post_index_link2">
  <%= link_to 'New Post', new_post_path %>
    </div>
</div>

app/views/posts/new.html.erb
<div id="post_new">
<h1>New post</h1>
<br/>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
 </div>

app/views/posts/show.html.erb
<p id="notice">
  <% notice %></p>
<div id="post_show">
  <br/>

  <h1>
    <center><b><%= Filteranddiscount.runfilter(@post.title) %></b></center>
  </h1>
  <br/> <br/><br/>

  <div align="right" style="margin-right:50px;">
    <b>Author:</b>
    <% if @post.user.profiles.first != nil %>
        <%= @post.user.profiles.first.firstname %>
    <% else %>
        <%= @post.user.email %>
    <% end %>
  </div>
  </br>
  </br>
  <div>
    <%= Filteranddiscount.runfilter(@post.text) %>
  </div>
  <br/><br/>

  <div>********************************************************************************</div>
  <h2><u>Comments:</u></h2>
  <% @post.commentps.each do |commentp| %>

      <p>
        <%= Filteranddiscount.runfilter(commentp.body) %>
      </p>
      <% if current_user and current_user.admin == 'manager' %>
          <p align="right">
            <%= link_to 'Destroy Comment', [commentp.post, commentp],
                        method: :delete,
                        data: {confirm: 'Are you sure?'} %>
          </p>
      <% end %>
      <div>................................................................................</div>
  <% end %>
  <br/>

  <div align="center">
    <h2>Leave your comment:</h2>
    <%= form_for([@post, @post.commentps.build]) do |f| %>

        <p>
          <% f.label :body %><br/>
          <%= f.text_area :body %>
        </p>

        <p>
          <%= f.submit 'submit' %>
        </p>
    <% end %>
  </div>



  <% if (current_user and current_user.admin == 'customer') or (current_user and current_user.admin == 'worker') %>
      <%= link_to 'View Posts', posts_path %> |
      <%= link_to 'View Yoursite', profiles_path %>

  <% else %>
      |<%= link_to 'View Posts', posts_path %>|
  <% end %>
</div>